version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge